### ISSUE TITLE
Version 1.0 Docker - Buildfehler

### ISSUE THREAD

**Issue by bneidhold** [gematik/KOB-Testsuite#12]
Umgebung: unverändertes Repository, Win11, Docker Desktop, docker compose -f dc-testsuite.yml up (und alle FAQs der Seite durchgearbeitet).
Container startet nicht....

Hier scheint das Setup nicht robust genug. 

2024-11-30 11:05:32 kob-testsuite  | [INFO] writing file /app/target/generated-sources/openapi/.openapi-generator-ignore
2024-11-30 11:05:32 kob-testsuite  | [INFO] writing file /app/target/generated-sources/openapi/.openapi-generator/VERSION
2024-11-30 11:05:32 kob-testsuite  | [INFO] writing file /app/target/generated-sources/openapi/.openapi-generator/FILES
2024-11-30 11:05:32 kob-testsuite  | ################################################################################
2024-11-30 11:05:32 kob-testsuite  | # Thanks for using OpenAPI Generator.                                          #
2024-11-30 11:05:32 kob-testsuite  | # Please consider donation to help us maintain this project 🙏                 #
2024-11-30 11:05:32 kob-testsuite  | # https://opencollective.com/openapi_generator/donate                          #
2024-11-30 11:05:32 kob-testsuite  | ################################################################################
2024-11-30 11:05:32 kob-testsuite  | [INFO] 
2024-11-30 11:05:32 kob-testsuite  | [INFO] --- resources:3.3.1:resources (default-resources) @ kob-testsuite ---
2024-11-30 11:05:32 kob-testsuite  | [INFO] Copying 1 resource from src/main/resources to target/classes
2024-11-30 11:05:32 kob-testsuite  | [INFO] ------------------------------------------------------------------------
2024-11-30 11:05:32 kob-testsuite  | [INFO] BUILD FAILURE
2024-11-30 11:05:32 kob-testsuite  | [INFO] ------------------------------------------------------------------------
2024-11-30 11:05:32 kob-testsuite  | [INFO] Total time:  3.205 s
2024-11-30 11:05:32 kob-testsuite  | [INFO] Finished at: 2024-11-30T10:05:32Z
2024-11-30 11:05:32 kob-testsuite  | [INFO] ------------------------------------------------------------------------
2024-11-30 11:05:32 kob-testsuite  | [ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.3.1:resources (default-resources) on project kob-testsuite: copying /app/src/main/resources/psTestdriver.yaml to /app/target/classes/psTestdriver.yaml failed with FileSystemException: /app/target/classes/psTestdriver.yaml: Operation not permitted -> [Help 1]
2024-11-30 11:05:32 kob-testsuite  | [ERROR] 
2024-11-30 11:05:32 kob-testsuite  | [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
2024-11-30 11:05:32 kob-testsuite  | [ERROR] Re-run Maven using the -X switch to enable full debug logging.
2024-11-30 11:05:32 kob-testsuite  | [ERROR] 
2024-11-30 11:05:32 kob-testsuite  | [ERROR] For more information about the errors and possible solutions, please read the following articles:
2024-11-30 11:05:32 kob-testsuite  | [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by Arkinator** [comment]
Sind dran, danke für den Hinweis

**Comment by Arkinator** [comment]
Das Problem scheint sehr spezifisch zu sein, aber wir konnten es nachstellen und ein Fix ist in der Pipeline. Als Workaround hat bei uns geklappt entweder das target verzeichnis auf dem host-rechner zu löschen oder einfach volle rechte auf dem gesamten git-ordner einzuräumen. Bitte verifizieren (wir sind auch dran...).

**Comment by bneidhold** [comment]
beide Tipps funktionieren nicht (nach dem löschen immer das selbe und auch volle Rechte geben - das lief vorher schon als Admin - hilft nix). 
wenn der Fehler kommt, liegt die Datei schon in target\classes\psTestdriver.yaml. Kann es sein, dass der Buildprozess die Datei 2x versucht da hin zu kopieren und kann es weiterhin sein, dass hier Parallelität im Spiel ist und mehrfaches gleichzeitiges kopieren ein Problem ist? Ich kenne mich da leider zu wenig aus.

**Comment by aprini** [comment]
Kann diesen Fehler bestätigen, hatte ich auch. Hat mich gezwungen das ganze mit pur maven zu versuchen.

**Comment by KillerCodeMonkey** [comment]
Ich bekomme auf einem frisch aufgesetzten Ubuntu 24.04. mit Docker version 27.3.1, build ce12230

```SH
/app/src/main/resources/psTestdriver.yaml [0:0]: unexpected error in Open-API generation
kob-testsuite  | java.lang.RuntimeException: Could not generate model 'action'
...
Caused by: java.nio.file.NoSuchFileException: /app/target/generated-sources/openapi/src/main/java/de/gematik/test/psTestdriver/dto/Action.java
kob-testsuite  |     at sun.nio.fs.UnixException.translateToIOException (UnixException.java:92)

```

**Comment by sproels** [comment]
[kob-start.log](https://github.com/user-attachments/files/17976349/kob-start.log)
Die java.lang.RuntimeException: Could not generate model 'action' kriege ich hier auch. Wiederholtes Löschen aller container, images und volumes sowie des github clones haben nicht geholfen. Anbei das komplette Start-Log.

System: Docker version 26.1.3 unter Rocky Linux release 8.10.

**Comment by KillerCodeMonkey** [comment]
geil... scheinbar wird der tomcat nicht immer korrekt beendet... schade

**Comment by KillerCodeMonkey** [comment]
Nun bekomme ich folgendes

```SH
Error creating bean with name 'messageQueue' defined in URL [jar:file:/home/user/.m2/repository/de/gematik/test/tiger-proxy/3.4.5/tiger-proxy-3.4.5.jar!/de/gematik/test/tiger/proxy/TigerProxyHealthIndicator.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'tigerProxy' defined in class path resource [de/gematik/test/tiger/proxy/TigerProxyConfigurator.class]: Failed to instantiate [de.gematik.test.tiger.proxy.TigerProxy]: Factory method 'tigerProxy' threw exception with message: Exception while binding MockServer to port 443
```

**Comment by Arkinator** [comment]
Die Vielzahl der Fehler hier macht ein konkretes Helfen eher schwer... ;)

* "no selectable cipher suite" ist der Fehler, wenn ein nicht unterstützter Host angefragt wurde. Es werden vier Zertifikate mitgegeben, as1, as2, idp und localhost. Bitte verifizieren das Sie tatsächlich die 1.0er Version benutzen und das Sie eines dieser vier Hosts anfragen. Im Zweifelsfall würde ich per Wireshark im ClientHello auf sie SNI-Extension schauen, was dort als Host angegeben wird. Das ist der maßgebliche Punkt. Können Sie mir diese Info geben? Vielen Dank

* Ja, der Tomcat wird nur über den Quit-Button auf der Workflow-UI ordnungsgemäß herunter gefahren. Known behaviour.

* Das Generieren-Problem können wir intern tatsächlich nur auf manchen Rechnern nachvollziehen. Wir sind dran :/

**Comment by KillerCodeMonkey** [comment]
@Arkinator danke für die Hilfe :)

Was genau kann ich denn von meiner Seite bzgl der Cipher-Suite falsch gemacht haben?
in meiner /etc/hosts sind die beiden Einträge vorhanden.
Ich starte egal ob über mvn oder docker die Testsuite und öffne die Workflow UI.

Da habe ich doch gar keinen Einfluss darauf, welcher Host wie angesprochen wird?

**Comment by ClausDampsoft** [comment]
Wir haben das gleiche Problem mit der TLS-Verbindung. Ja wird sind auf 1.0 unterwegs und haben die beiden Aktensystem in der hosts. Allerdings läuft die Testsuite nicht auf localhost sondern auf eine anderen Maschine.

**Comment by Arkinator** [comment]
@ClausDampsoft hab ich im Chat geantwortet, für @KillerCodeMonkey nochmal eine ausführliche Erklärung: 

Beim Handshake schaut der Proxy nach, welches Zertifikat er dem Client präsentieren soll. Dafür schaut er in die SNI-Extension des Client-Hello, dort steht ein Servername. Mit diesem geht er nun zuerst zur Liste der fest hinterlegten Zertifikate (die Liste ist unter tiger.yaml: tigerProxy.tls.serverIdentities). Die Zertifikate sollten für alle hier notwendigen Server passen (as1, as2, idp und localhost, für den fall das man mal pingen will).

Wenn jedoch KEIN Zertifikat gefunden wird, dann generiert sich der Server eines dynamisch selber. Aufgrund eines Bugs im Tiger-Framework ist dieses dynamische Zertifikat immer ein RSA-Zertifikat. Und weil wir mittlerweile fest eine Liste von Cipher-Suiten enforcen geht das immer daneben (in der gemeinsamen Liste gibt es keine Ciphersuite die RSA enthält). 

Der Fehler ist also zum einen hoffentlich bald Geschichte (Tiger-Update), zum anderen weißt er aber auch klar darauf hin das hier ein "komischer" FQDN abgefragt wird. Da würde ich meine Analyse hin verlagern: Per Wireshark mal in den Handshake schauen, Client-Hello, SNI-Extension. Denn letztlich wird der Handshake hier immer daneben gehen: Der SNI passt nicht zu dem, was die Testsuite machen soll. Es gibt also irgendeinen Setup-Fehler auf eurer Seite. Das der so schwer zu finden ist liegt an uns und wird gefixt.

**Comment by KillerCodeMonkey** [comment]
@Arkinator Danke nochmals.

Leider hatte ich nicht die Zeit das mit Wireshark zu checken.

Ich weiß nur nicht woher ein falsches setup kommen sollte, da ich alles auf einem taufrischen Ubuntu 22.04 und 24.04 probiert habe. 

Einzige Besonderheit ist vlt, dass unser Konnektor nicht lokal, sondern von tsystems in der Cloud betrieben wird und wir per vpn drauf zugreifen.

Das Abrufen der eML bei IBM funzt auch wie gehabt. (Ohne testsuite)

Also selbst ,wenn ich in Wireshark iwas komisches sehen würde, wüsste ich nicht, was zu tun ist.

Vielleicht kann sich ja @ClausDampsoft bei mir melden, und umgekehrt, falls es eine Spur gibt.

**Comment by Arkinator** [comment]
Bei @ClausDampsoft läuft die testsuite auf einem anderen rechner, das sind nochmal ganz eigene probleme :)

aber VPN haben wir eigentlich auch lokal im Einsatz, ohne Probleme... Bei uns klappt der Zugriff auf die Server nur über einen weiteren Proxy (also ps -> tiger-proxy -> vpn-proxy -> AS), den müssen wir dann natürlich in der tiger.yaml konfigurieren. ein entsprechendes Beispiel ist auskommentier in der datei vorhanden.

Das beschriebene Problem klingt aber genau nicht nach einem problem vom Tiger-Proxy zum AS, sondern vom PS zum tiger-proxy. Und das wiederum spielt sich ja alles auf dem lokalen rechner ab. daher vllt erstmal mit curl -v über den Tiger-proxy auf das Aktensystem zugreifen, ggf mit wireshark in den SNI des Client-hellos schauen... ich fürchte da führt kein weg drum herum

**Comment by KillerCodeMonkey** [comment]
@Arkinator ich habe kp, wie ich Wireshark bedienen muss. Hast du zufällig eine Idee, was ich da mitscheiden muss / ip/host?

naja aber ich komme doch gar nicht soweit, dass ich im PVS iwas machen kann.

Ich öffne die Workflow UI und dann wird ja noch einiges initialisiert und da kommt der TLS Fehler....
Ich würde mich freuen, wenn ich schon an dem Punkt wäre, dass ich mit meine PVS loslegen kann.

Die Workflow UI initalisiert richtig auf einer Windows-Maschine, ohne dass ich iwas weiteres tun muss.

**Comment by Arkinator** [comment]
es geht hier etwas durcheinander :) empfehlung: kannst du ein ANFPS oder ANFEPA Ticket mit einem kompletten LOG-output aufmachen? alternativ hier ein neues ticket. 
Wir brauchen:
Welches OS, welche Versionen von mvn, jdk, Docker, Wie wurde es gestartet (cmdline copy), console output

**Comment by KillerCodeMonkey** [comment]
Ich würde gern hier ein neues Ticket aufmachen und nicht auch noch in den anderen Tools rumfummeln müssen, wenn das geht :D

**Comment by Arkinator** [comment]
ANFPSE wäre der ort: https://service.gematik.de/servicedesk/customer/portal/35/create/120
Oder hier ein neues mit den gelisteten Informationen.

**Comment by KillerCodeMonkey** [comment]
@Arkinator #15 lass mich wissen, ob iwas fehlt.

**Comment by eitzenbe** [comment]
Ticket closed / delegate ticket #15
