### ISSUE TITLE
Maven KOB für nur ein Aktensystem - Durchlauf mit kleinen Ecken und Kanten

### ISSUE THREAD

**Issue by bneidhold** [gematik/KOB-Testsuite#13]
**Hinweis für den FAQ Bereich:**
Wenn man dies unter Windows in der Powershell ausführt, muss ein --% eingefügt werden um die Parameter korrekt zu übergeben:
mvn clean verify --% -Dcucumber.filter.tags=@IBM

**Fehlerausgaben auf der Console trotz erfolgreicher Testung**
Nach erfolgreicher Testung für IBM und Quittierung in der Weboberfläche wird tatsächlich das ZIP-File kob-testsuite-1.0.0-test-report.zip erstellt. Verwirrend ist aber, dass gleichzeitig Fehlerausgaben auf der Console erscheinen:

![image](https://github.com/user-attachments/assets/0de205bd-672e-48bf-b87d-87b010b31439)

**Fehlende Infos zum Gesamtprozess**
- Trotz Hinweis um Vorfeld, gibt es keine Detailaussage, wie der Screenshot zu erstellen ist, wenn man das PDF der EML im PS auf Knopfdruck generiert und dann im PDF-Viewer anzeigt. Soll Screen vom Acrobat Reader erstellt werden oder vom Button im PS?
- Ich kann nicht zweifelsfrei aus dem Seite herauslesen, dass es für den derzeitigen KOB ausreicht, dass man nur RISE oder nur IBM oder beides ausführt -> bitte präzisieren

**Comment by Arkinator** [comment]
* Die Beschreibung des Screenshots kommt "von oben", ich geb das mal weiter.
* Änderung der Readme kommt soon (tm). Die KOB sollte klappen wenn der Durchlauf grün ist mit einem drei drei optionen (IBM, RISE oder KOB)

**Comment by KillerCodeMonkey** [comment]
habe das problem gefunden und #21 eröffnet

**Comment by bneidhold** [comment]
nur zur Info ich bin inzwischen mit der KOB für beide Aktensysteme durch. Habe es gezwungenermaßen mit maven lokal gemacht.
Wäre schön, wenn für die 2. Runde in 2 Monaten die Cocker-Variante dann robust läuft ;-).

**Comment by eitzenbe** [comment]
Ticket closed due to new release / no more issue
