### ISSUE TITLE
Upload der zip Archivs bei TITUS nicht möglich, wenn die report Dateien in einen Unterordner gepackt werden

### ISSUE THREAD

**Issue by KillerCodeMonkey** [gematik/KOB-Testsuite#16]
Eine Kollegin hatte bereits Kontakt zum KIG, leider waren die Antworten nicht sehr hilfreich.

Es wird versucht das Archiv - so wie es die Testsuite generiert - bei TITUS hochzuladen.
Leider kommt dann folgende Fehlermeldung.

![Bildschirmfoto 2024-12-03 um 14 34 58](https://github.com/user-attachments/assets/69f88a83-119a-4960-a5a1-e40a86a62877)

Der serenity report und die json Dateien sind im Archiv enthalten.

![Bildschirmfoto_20241203_153427](https://github.com/user-attachments/assets/23d3d79f-7422-48ba-b850-47ea9996fcb5)

Hat sich vielleicht die Benamung der Dateien im Archiv geändert und wurden nicht angepasst?
Laut KIG sieht das Archiv korrekt aus.

Vielen Dank.

**Comment by KillerCodeMonkey** [comment]
@eitzenbe steht in dem zip nicht iwas vertrauliches drin? client keys etc?

**Comment by eitzenbe** [comment]
Hmm not that I knew, aber gerne auch per mail an t.eitzenberger@gematik.de

**Comment by KillerCodeMonkey** [comment]
PS: ich hoffe, dass da was eineindeutiges für den Client in der RU drinsteht, sonst wäre der Test iwie nicht so sicher und man könnte das Ergebnis ja einfach mit anderen teilen und alle freuen sich, dass sie bestehen :D

**Comment by eitzenbe** [comment]
Hmmm das zip hat die report files in einem subverzeichnis, daher failed Titus, repack ohne Unterverzeichnis sollte das Problem lösen. Mir ist aber nicht klar woher das kommt, das maven assembly packt das flat ein...

**Comment by eitzenbe** [comment]
Wegen Eineindeutigkeit: Naja gewinnen tut damit niemand was, sprich wenn ich mich durch die Seglerscheinschulung schummle und dann die Reise über den Atalntik ohne ausreichend Skills antreten muss .... #goFigure :)

**Comment by eitzenbe** [comment]
@KillerCodeMonkey Wie wurde das ZIP denn erstellt/aus dem Container geholt? Oder per maven direkt am Host?

**Comment by KillerCodeMonkey** [comment]
Das ist nur verschschtelt, weil ich es vorher entpackt und wieder gepackt hatte. 

Aber auch flat erhalten wir "Fehler beim validieren des Testberichts" in Titus.

**Comment by eitzenbe** [comment]
wir schauen rein, eigentlich sollte noch eine detailierter Fehlermeldung auftauchen #pleaseShare

**Comment by eitzenbe** [comment]
? d.h. Validierung hat geklappt?

**Comment by KillerCodeMonkey** [comment]
Nein klappt nicht. Es kommt eine benachrichtigung / toast message in Titus, dass die Daten nicht validiert werden kann.

Mehr details erhalten wir nicht. 
Titus schickt auch keinen Request, um die dabei hochzuladen... also validiert Das Frontend von Titus die Datei.

Keine Ahnung, was wir falsch machen könnten. 

Haben den Upload mit MacOS chrome und windows chrome versucht. Bei beiden kommt die gleiche Meldung in Titus.
