### ISSUE TITLE
Fehler beim Upload bei Titus

### ISSUE THREAD

**Issue by RobertN-Dev-DENS** [gematik/KOB-Testsuite#19]
Hallo zusammen,

ich bekomme einen erfolgreich erstellten Testbericht (IBM/Rise passed) nicht hochgeladen.
Firefox, Chrome sowie Microsoft Edge probiert

Java 17
Maven 3.9.9
Testsuite 1.0.1
Windows 11

![Tiger-Log](https://github.com/user-attachments/assets/d5b06d06-6e8d-4cd9-a432-2426975ec647)
![Fehler-Upload](https://github.com/user-attachments/assets/ad03e230-bc87-4d37-94c9-a9fe786d0808)

Beste Grüße

**Comment by KillerCodeMonkey** [comment]
@RobertN-Dev-DENS habt ihr die Tests mit Docker oder MVN ausgeführt?

auf meinen Ubuntu hab ich tatsächlich das Archiv entpackt und nochmal die Permissions gesetzt, dass die Dateien jeder bearbeiten darf.

```sh
chmod -R 777 ./
```

im entpackten Archiv und dann die einzelnen Dateien neu verpackt.

Außerdem aufpassen:

- es darf keinen Unterordner im Archi geben
- versteckt Dateien/Ordner anzeigen lassen und schauen, ob noch iwelche anderen Dateien enthalten sind.

Eine Frage von mir:
Wie habt ihr RISE zum Laufen bekommen?

Bei mir failed immer:
`Und TGR prüfe aktuelle Antwort stimmt im Knoten "$.body.decrypted.header.[~'content-type']" überein mit "(application\/fhir\+json|application\/pdf|text\/html)"`

Wenn ich die eML abrufen (egal ob, xhtml, pdf, ...), ist der Content-Type auf der Response von Rise nicht korrekt gesetzt.

**Comment by RobertN-Dev-DENS** [comment]
Habe mvn verwendet. Habe ein Ticket bei Titus aufgemacht und bekam unmittelbar eine Antwort. Das Problem konnte gelöst werden. Der Auftrag für die Beantragung war zu alt. Den einfach löschen und einen neuen anlegen. Dann die aktuelle Testversion 2 wählen. Dann funktioniert auch der Upload. Vielleicht funktioniert Rise jetzt bei euch. Da wurde in den letzten Tagen wohl ordentlich geschraubt.

**Comment by KillerCodeMonkey** [comment]
@RobertN-Dev-DENS gerade probiert und läuft noch nicht. 
Wir brauchen ja erstmal nur ein Aktenanbieter... mal sehen.

Finde es nur komisch.

PS: Das Problem hatten wir auch noch... haben halt nicht mitbekommen, dass es da in TITUS eine neue Testversion gab...

**Comment by KillerCodeMonkey** [comment]
@RobertN-Dev-DENS scheinbar darf man im Accept Header den man erwartet kein Charset angeben.
IBM nimmt das raus. RISE scheint stumpf den Content-Type zurück zu geben, den man schickt. -.-

wir senden `Content-Type: text/html;charset=utf-8` ohne das charset geht es...

@Arkinator ich weiß nicht was hier die Gematik/Spezifikation erwartet... Aber das Setzen eines Charsets sollte erlaubt sein. Daher wäre es schön, wenn man nicht hart auf einen festen String prüfen würde...
