### ISSUE TITLE
 KOB-Testsuite 1.0.1 kann nicht gestartet werden

### ISSUE THREAD

**Issue by kre-medisoftware** [gematik/KOB-Testsuite#20]
Ich bekomme einen Fehler beim Starten der KOB-Testsuite 1.0.1
```
C:\Users\Karsten\source\repos\KOB\KOB-Testsuite>docker compose -f dc-testsuite.yml up
[+] Running 3/3
 ✔ Network dc-testsuite-kob_default  Created                                                                       0.0s
 ✔ Volume "kob-testsuite-maven"      Created                                                                       0.0s
 ✔ Container kob-testsuite           Created                                                                       0.1s
Attaching to kob-testsuite
kob-testsuite  | env: ‘bash\r’: No such file or directory
kob-testsuite  | env: use -[v]S to pass options in shebang lines
kob-testsuite exited with code 127
```

**Comment by CEiderEVIDENT** [comment]
Gleiches Problem, siehe https://service.gematik.de/servicedesk/customer/portal/13/ANFEPA-3043

**Comment by KillerCodeMonkey** [comment]
Ich habe kurz mal gegoogled:
https://stackoverflow.com/questions/70380310/docker-env-bash-r-no-such-file-or-directory

vielleicht mal mit einem anderen line ending versuchen.

es gibt ja 
OSX, Linux: LF (\n)
Legacy MacOS (MacOS 9 and earlier): CR (\r)
Windows: CR LR pair (\r\n)

Normalerweise sollten diese \LF sein.

**Comment by eitzenbe** [comment]
Guten Morgen, Sie scheinen beim git clone die Zeilenendungen falsch konfiguriert zu haben.

[Siehe Doku](https://docs.github.com/de/get-started/getting-started-with-git/configuring-git-to-handle-line-endings)

**Comment by Arkinator** [comment]
nachgetestet mit frischem checkout auf macos: bei mir läufts. 
`git config core.autocrlf ` ist bei mir auf input, as it should, und ich hab MacOS.

Damit das ganze resilienter läuft fügen wir eine entsprechende .gitattributes hinzu.

**Comment by kre-medisoftware** [comment]
Das hat mir alles nicht geholfen.
Ich habe jetzt die KOB-Testsuite als ZIP-File vom github geladen und die **run.sh** (ist im ZIP-File als MacOS Variante \r enthalten) im Zielverzeichnis ersetzt.
Damit startet die KOB-Testsuite

**Comment by CEiderEVIDENT** [comment]
Naja der Workaround der Einstellung zu den Zeielumbrüche funktioniert. Nur dies ist nicht die Standardeinstellung in unserem git-tool (Sourcetree). Nach Umstellung wird der gesamt Quellcode unseres Projektes als Änderung (der Zeilenumbrüche) erfasst.
Auch nicht zielführend.

Meiner Meinung nach muss das Paket hier angepasst werden!

**Comment by KillerCodeMonkey** [comment]
Ich denke das wird sich erledigen, wenn hier die .gitattributes bereitgestellt werden.

Temporär könntest du diese selbst in den kob-testsuite Ordner anlegen.
