### ISSUE TITLE
Content-Type check auf application/pdf|text/html erlaubt kein charset

### ISSUE THREAD

**Issue by KillerCodeMonkey** [gematik/KOB-Testsuite#21]
Wir haben uns gewundert, warum der RISE Test nie durchlief.
Leider senden wir noch zum Accept-header ein charset.

Dieses liefert IBM nicht, Rise jedoch mit zurück.

Dann failed der Test, obwohl der Conent-Type der Response korrekt ist.
Entfernen wir das charset, läuft der Test.

Beispiel:

```
GET /epa/medication/render/v1/eml/xhtml HTTP/1.1
Host: HOST
...
Content-Type: application/octet-stream;charset=utf-8
Accept: text/xhtml;charset=utf-8
...
```

IBM liefert auf der inneren Antwort dann

`Content-Type: text/xhtml`

Rise:

`Content-Type: text/xhtml;charset=utf-8`

IBM test läuft, RISE nicht.
Nehme ich das Charset weg, funktioniert der Test.

Hier sollte die Regex erweitert bzw. gelockert werden.

Darüberhinaus loggt die Testsuite im Terminal/Konsole, dass der Fehler am non-PU Header liegt, was falsch ist.

**Comment by fnoGematik** [comment]
Hallo @KillerCodeMonkey ,

mir ist gestern auch aufgefallen, dass das RISE AS momentan den Accept Header einfach (ungeprüft) als Content-Type bei der eML Abfrage in der Response zurück liefert. In dem Fall war es sogar "application/json" für ein PDF. Ein Ticket dazu habe ich bereits im Service Desk eingestellt.

Viele Grüße,

**Comment by fnoGematik** [comment]
Hallo @KillerCodeMonkey,

wir haben soeben die KOB Testsuite in der Version 1.0.2 veröffentlicht. Darin ist auch die Anpassung für ein optionales Charset beim Content-Type text/html enthalten (wildcard).

https://github.com/gematik/KOB-Testsuite/blob/main/src/test/resources/features/epa_3_0/kob_epa3_0.feature#L95

Viele Grüße,
