### ISSUE TITLE
Docker-.Image meldet BUILD FAILURE

### ISSUE THREAD

**Issue by lynn-lumen** [gematik/KOB-Testsuite#4]
Nach Ausführung der angegebenen Commandline "docker compose -f dc-testsuite.yml up"
meldet der Docker-Container beim hochfahren folgenden Fehler und beendet sich dann.

kob-testsuite  | [ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.12:report (jacoco-site) on project kob-testsuite: An error has occurred in JaCoCo report generation.: Error while creating report: null: EOFException -> [Help 1]

Was können wir hier tun um diesen Fehler zu vermeiden?

**Comment by fnoGematik** [comment]
Hallo @lynn-lumen ,

mittlerweile sind schon neuere Versionen der KOB-Testsuite veröffentlicht worden. Der Fehler deutet darauf hin, dass es sich um ein Zugriffsproblem /Rechteproblem handelt.
Vor dem Starten eines Docker Container mit einer neuen Version, bitte die vorherigen Docker Artefakte (Container, Volume) löschen - siehe FAQ in der Readme.
Tritt der Fehler immer noch mit der aktuellen Version der KOB-Testsuite auf?

Viele Grüße,
